version: "3.9"
services:
  angular-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG: production
    image: angular-web:latest
    container_name: angular-web
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
