version: "3.9"

services:
  appointments-front-staging:
    container_name: appointments-front-staging
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        API_BASE_URL: ${API_BASE_URL}
        NODE_ENV: ${NODE_ENV}
    env_file:
      - .env
    ports:
      - "4200:80"
    restart: always
    networks:
      - ${NETWORK_NAME}
    labels:
      - com.appointments.environment=staging

networks:
  appointments_network:
    external: true
